---

- name: Generate openssh key pair for access to Github
  openssh_keypair:
    path: "/home/jenkins/.ssh/id_rsa_gh"
  register: ssh_pub_key_gh

- name: Read Github token to authorize
  local_action: shell cat /home/lev/ansible-tuto/secret2
  register: gh_token

- name: debug
  debug:
    msg:
    - "ssh_pub_key_gh : {{ ssh_pub_key_gh.public_key }}"
    - "gh_token: {{ gh_token.stdout }}"
    - "ansible_facts: {{ ansible_facts['nodename'] }}"

- name: Authorize key with GitHub
  community.general.github_key: 
    name: Access Key for {{ ansible_facts['nodename'] }}
    token: "{{ gh_token.stdout }}"
    pubkey: "{{ ssh_pub_key_gh.public_key }}"
 

