---
- name: Install prerequirements from repo
  apt: name="{{ item }}" state=latest
  loop: "{{ pkgs }}"

- name: Install openjdk
  apt: name=openjdk-11-jdk state=latest
# state: present

- name: Add root certificate to trust store
  import_tasks: "add-ca.yml"

- name: Enable jenkins master
  import_tasks: "jenkins-master.yml"

- name: Install plugins
  import_tasks: "add-plugins.yml"

