---
# - hosts: all
#   become: true
#   vars:

- name: Update apt cache
  apt: update_cache=yes

- name: Install openssh-server
  apt: name=openssh-server state=latest

- name: Add public key
  copy:
    src: files/authorized_keys #"{{ item }}"
    dest: /home/user/.ssh/authorized_keys #"{{ path-public-key }}/{{ item }}"
    owner: user
    mode: 0644
#  with_fileglob:
#    - files/*
  notify:
    - restart openssh server
 

